from api.models.graph import Graph, Node, Edge
# node1 = Node("1", {"1": "Bijeljina"})
# node2 = Node("2", {"2": "Zvornik"})
# node3 = Node(3, {"3", "Novi Sad"})
# edge12 = Edge({}, node1, node2)
# edge13 = Edge({"distance": "100km"}, node1, node3)
# node1.edges.append(edge12)
# node1.edges.append(edge13)
# node3.edges.append(edge13)
# node2.edges.append(edge12)
# g = Graph(directed=False)
# g.add_node(node1)
# g.add_node(node2)
# g.add_edge(edge12)
# print(g)

# print(g.nodes, g.edges)

# g.remove_node(node3)

# print(g.nodes, g.edges)

moj_graf = Graph(None, None, False, None)
print(moj_graf)
n1 = Node("1", {"city": "Bijeljina"})
n2 = Node("2", {"city": "Zvornik"})
moj_graf.add_node(Node("1", {"city": "Bijeljina"}))
moj_graf.add_node(Node("2", {"city": "Zvornik"}))
print(moj_graf)
moj_graf.add_edge(Edge({"dist": "50km"}, n1, n2))
print(moj_graf)
moj_graf.remove_node(n2)
# moj_graf.remove_node(n2)
print(moj_graf)
n2 = Node("3", {"city": "Zvornik"})
e1 = Edge({"dist": "50km"}, n1, n2)
moj_graf.add_edge(e1)
print(moj_graf)
moj_graf.remove_node(n2)
print(moj_graf)
